const actionTypes = {
    PROGRAMMING_CATEGORY: "PROGRAMMING_CATEGORY",
    DESIGN_CATEGORY: "DESIGN_CATEGORY",
    SMM_CATEGORY: "SMM_CATEGORY",
    GET_PROGRAMMING_PROJECTS: "GET_PROGRAMMING_PROJECTS",
    GET_DESIGN_PROJECTS: "GET_DESIGN_PROJECTS",
    GET_SMM_PROJECTS: "GET_SMM_PROJECTS",
    PENDING:"_PENDING",
    FULFILLED:"_FULFILLED",
    REJECTED:"_REJECTED",
    COURSES_LIST:"COURSES_LIST"
}

export default actionTypes;